Construct planar graph function implemented and tested in main.cpp but currently a test case cannot be created in gtest due to make test not working  properly resulting in undefined reference to opencv function